//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FantasyGame__1.Story {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Stick {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Stick() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FantasyGame__1.Story.Stick", typeof(Stick).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are you gonna do with this big stick?|
        ///
        ///
        ///1.  Keep it as a stick
        ///2.  Use the wood to keep the fire going
        ///3.  Sharpen the stick with your knife make a spear
        ///.
        /// </summary>
        internal static string CFChoices {
            get {
                return ResourceManager.GetString("CFChoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You clamp the stick between your belt to keep it close and hurry back to the campfire where it&apos;s safe.|.
        /// </summary>
        internal static string CFStick1 {
            get {
                return ResourceManager.GetString("CFStick1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You walk back to the campfire and break the stick in pieces.|
        ///This&apos;ll keep you warm for a while!|
        ///If the circumstances were different you could almost enjoy the knispering sounds of the fire,|
        ///the warmth it gives, and the night sky above the trees.|.
        /// </summary>
        internal static string CFStick2 {
            get {
                return ResourceManager.GetString("CFStick2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You sit down next your campfire and start sharpening the tip of the stick.|
        ///Sitting here working on your spear brings you back to the times when you were younger,|
        ///goofing around with your big brother.|
        ///Reanacting stories father read to you two before bed, that left such a big impression
        ///that you couldnt help but stay awake untill it became impossible to keep your eyes open.|
        ///Kinda like you&apos;re feeling right now...|||
        ///|
        ///Wow! Stay awake. This is not the time to fall asleep!|
        ///You pull yourself together [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CFStick3 {
            get {
                return ResourceManager.GetString("CFStick3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You look around you to see what is out there.|
        ///Even though it&apos;s very dark you can distinguish the shape of a pretty big fallen branch close by.|
        ///You decide to walk over there and grab it.|.
        /// </summary>
        internal static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
    }
}
